**10 function to show magic in array**:

1.**Stacking**:

              1.Horizontal Stacking:hstack() function will stack append one aarray at the end of another.
              2.Vertical Stacking:vstack() function will stack one array on another.

2.**Comparing** **Two** **Arrays**:

              1.allclose():This function finds whether two arrays are equal or approximately equal to each other based on some tolerance value if the shape of both arrays is the same.
              2.Equals():It compares each element of both arrays and if elements matched returns True.

3.**Einstein** **Summation** **Conventions**:
              
              Einsum():This function is used to compute many multi-dimensional and linear algebraic operations on arrays.

4.**Statistical** **Analysis**:

              Histogram():It is an important statistical analysis function of NumPy that computes histogram values for a set of data.

5.**Standard** **Deviation** **and** **Variance**:
              
              1.str():This function of numpy that calculate standard deviation on axis.
              2.var():This function of numpy that calculate variance on axis.
    
6.**Spliting**:

              1.Horizontal Split:hsplit() function will split the data horizontally into n equal parts.
              2.Vertical Split:vsplit() function will split the data vertically into n equal parts.



              


In [ ]:
import numpy as np

In [ ]:
#1st function
#horizontal stacking
array_1 = np.array([1,2,3,4,5,6,7,8,9,10])
array_2 = np.array([11,12,13,14,15,16,17,18,19,20])
hstack_array = np.hstack((array_1,array_2))
hstack_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#2nd function
#verical stacking on above arrays
vstack_array = np.vstack((array_1,array_2))
vstack_array

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
#3rd function
"""np.allclose function finds whether two arrays are equal or approximately
equal to each other based on some tolerance value if the shape of both arrays
is the same.here if we take tolerance as 1.0 so we can get True value."""

from numpy.core.getlimits import array
array_3 = np.array([0.1,0.2,0.3,0.4,0.5])
array_4 = np.array([0.6,0.7,0.8,0.9,1.0])
tolerance = 0.5
print(np.allclose(array_3,array_4,tolerance))

False


In [ ]:
#4th function
''' Equals
It compares each element of both arrays and if elements matched returns True.'''
array_5 = np.array([1,2,3,4,5])
array_6 = np.array([1,1,3,4,1])
equals_array = np.equal(array_5,array_6)
equals_array

array([ True, False,  True,  True, False])

In [ ]:
#5th function
"""einsum() is used to compute many multi-dimensional and linear algebric
operations on arrays."""

array_7 = np.arange(1,10).reshape(3,3)
array_8 = np.arange(21,30).reshape(3,3)
print("Your 1st array:\n",array_7)
print("Your 2nd array:\n",array_8)

#Extracts diagonals
diagonals_array = np.einsum('ii->i',array_7)
print("Diagonal of 1st Array:\n",diagonals_array)

#Transpose
transpose_array = np.einsum('ji',array_8)
print("Transpose of 2nd Array:\n",transpose_array)

#matrix multiplication
matrix_array = np.einsum('ij,jk',array_7,array_8)
print("Matrix Multiplication:\n",matrix_array)

#sum of diagonal
print("sum of your 1st arrays diagonal is:",np.einsum('ii',array_7))

Your 1st array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Your 2nd array:
 [[21 22 23]
 [24 25 26]
 [27 28 29]]
Diagonal of 1st Array:
 [1 5 9]
Transpose of 2nd Array:
 [[21 24 27]
 [22 25 28]
 [23 26 29]]
Matrix Multiplication:
 [[150 156 162]
 [366 381 396]
 [582 606 630]]
sum of your 1st arrays diagonal is: 15


In [ ]:
#6th function
"""histogram() function is an important statistical analysis function of NumPy
that computes histogram values for a set of data."""

array_9 = np.array([[3,4,5,6],
                    [6,7,2,6]])
histo_array = np.histogram(array_9)
print("Histogram is :\n",histo_array)


Histogram is :
 (array([1, 0, 1, 0, 1, 0, 1, 0, 3, 1]), array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ]))


In [ ]:
#7th function
"""str() function will define standard deviation by axis.
here we take array_9."""

row_std_array = np.std(array_9,axis=1)
print("Row wise standard deviation:",row_std_array)

col_std_array = np.std(array_9,axis=0)
print("colomn wise standard deviation:",col_std_array)


Row wise standard deviation: [1.11803399 1.92028644]
colomn wise standard deviation: [1.5 1.5 1.5 0. ]


In [ ]:
#8th function

"""var() function will define variance by axis.
here we take array_9"""

row_var_array = np.var(array_9,axis=1)
print("Row wise variance :",row_var_array)

col_var_array = np.var(array_9,axis=0)
print("Colomn wise variance:",col_var_array)


Row wise variance : [1.25   3.6875]
Colomn wise variance: [2.25 2.25 2.25 0.  ]


In [ ]:
#9th function
"""hsplit function will split the data horizontally into n equal parts"""

two_array = np.hsplit(array_9,2) #array_9 splits data into 2parts
print("two equals part :",two_array)

four_array = np.hsplit(array_9,4)#array_9 splits data into 4parts
print("Four equals part:",four_array)

two equals part : [array([[3, 4],
       [6, 7]]), array([[5, 6],
       [2, 6]])]
Four equals part: [array([[3],
       [6]]), array([[4],
       [7]]), array([[5],
       [2]]), array([[6],
       [6]])]


In [ ]:
#10th function
"""vsplit function will split data vertically into n equals parts"""

t_a = np.vsplit(array_9,2)
print("Vertically two equal parts:",t_a)

Vertically two equal parts: [array([[3, 4, 5, 6]]), array([[6, 7, 2, 6]])]
